package main

// config is a representation of the TOML configuration typically
// specific in scoring.conf.
type config struct {
	DisableRemoteEncryption bool
	Local                   bool
	Shell                   bool
	EndDate                 string
	Name                    string
	OS                      string
	Password                string
	Remote                  string
	Title                   string
	User                    string
	Version                 string
	Platform                string `toml:"platform"`
	Desktop                 string `toml:"desktop"`
	Autologin               string `toml:"autologin"`
	Check                   []check
}

// check is the smallest unit that can show up on a scoring report. It holds all
// the conditions for a check, and its message and points (autogenerated or
// otherwise).
type check struct {
	Message  string
	Hint     string
	Points   int
	Category string

	Fail         []cond
	Pass         []cond
	PassOverride []cond
}

// cond, or condition, is the parameters for a given test within a check.
type cond struct {
	Hint string
	Type string

	Path          string
	Cmd           string
	User          string
	Group         string
	Name          string
	Key           string
	Value         string
	After         string
	regex         bool
	unknownFields []string
}
