package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"path/filepath"
	"sort"
	"strconv"
)

const contractSchema = "condition-availability-v1"

var freeBSDConditionMethods = []string{
	"AccountLocked",
	"BasePackageInstalled",
	"BaseUpdateChecksEnabled",
	"Command",
	"CommandContains",
	"CommandOutput",
	"DirContains",
	"FileACL",
	"FileContains",
	"FileEquals",
	"FileFlagSet",
	"FileOwner",
	"FirewallAvailable",
	"FirewallEnabled",
	"FirewallRulesLoaded",
	"FirewallUp",
	"JailRunning",
	"KernelVersion",
	"PackageUpdateChecksEnabled",
	"PasswordAuthenticationDisabled",
	"PasswordChanged",
	"PathExists",
	"PermissionIs",
	"PkgAuditClean",
	"ProgramInstalled",
	"ProgramVersion",
	"RunningInJail",
	"ServiceEnabled",
	"ServiceUp",
	"SysctlValue",
	"UserExists",
	"UserInGroup",
}

var legacyRegexConditionMethods = []string{
	"CommandContains",
	"DirContains",
	"FileContains",
}

var freeBSDRegexConditionMethods = []string{
	"CommandContains",
	"DirContains",
	"FileContains",
	"ProgramVersion",
	"SysctlValue",
}

type availabilityContract struct {
	Schema  string   `json:"schema"`
	Linux   []string `json:"linux"`
	Windows []string `json:"windows"`

	linuxRequired   map[string][]string
	windowsRequired map[string][]string
}

func discoverAvailability(root string) (availabilityContract, error) {
	linux, linuxRequired, err := discoverMethods(root, "linux")
	if err != nil {
		return availabilityContract{}, err
	}
	windows, windowsRequired, err := discoverMethods(root, "windows")
	if err != nil {
		return availabilityContract{}, err
	}
	return availabilityContract{
		Schema:          contractSchema,
		Linux:           linux,
		Windows:         windows,
		linuxRequired:   linuxRequired,
		windowsRequired: windowsRequired,
	}, nil
}

func discoverMethods(root, goos string) ([]string, map[string][]string, error) {
	ctx := build.Default
	ctx.GOOS = goos
	ctx.GOARCH = "amd64"
	ctx.CgoEnabled = false
	pkg, err := ctx.ImportDir(root, build.IgnoreVendor)
	if err != nil {
		return nil, nil, fmt.Errorf("select %s files: %w", goos, err)
	}

	methods := make(map[string][]string)
	fset := token.NewFileSet()
	for _, name := range append(pkg.GoFiles, pkg.CgoFiles...) {
		path := filepath.Join(root, name)
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if ok && isConditionMethod(fn) {
				required, err := requiredConditionFields(fn)
				if err != nil {
					return nil, nil, fmt.Errorf("inspect %s.%s: %w", path, fn.Name.Name, err)
				}
				methods[fn.Name.Name] = required
			}
		}
	}

	names := make([]string, 0, len(methods))
	for name := range methods {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, methods, nil
}

func isConditionMethod(fn *ast.FuncDecl) bool {
	// Exported matching methods define the public condition surface because runtime reflection exposes only exported methods.
	if !ast.IsExported(fn.Name.Name) {
		return false
	}
	if fn.Recv == nil || len(fn.Recv.List) != 1 || fn.Type.Params.NumFields() != 0 || fn.Type.Results == nil || len(fn.Type.Results.List) != 2 {
		return false
	}
	receiver, ok := fn.Recv.List[0].Type.(*ast.Ident)
	if !ok || receiver.Name != "cond" {
		return false
	}
	first, firstOK := fn.Type.Results.List[0].Type.(*ast.Ident)
	second, secondOK := fn.Type.Results.List[1].Type.(*ast.Ident)
	return firstOK && secondOK && first.Name == "bool" && second.Name == "error"
}

func requiredConditionFields(fn *ast.FuncDecl) ([]string, error) {
	required := make(map[string]struct{})
	var inspectErr error
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || selector.Sel.Name != "requireArgs" {
			return true
		}
		for _, argument := range call.Args {
			literal, ok := argument.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				inspectErr = fmt.Errorf("requireArgs arguments must be string literals")
				return false
			}
			field, err := strconv.Unquote(literal.Value)
			if err != nil {
				inspectErr = fmt.Errorf("decode requireArgs field: %w", err)
				return false
			}
			required[field] = struct{}{}
		}
		return false
	})
	if inspectErr != nil {
		return nil, inspectErr
	}
	fields := make([]string, 0, len(required))
	for field := range required {
		fields = append(fields, field)
	}
	sort.Strings(fields)
	return fields, nil
}

func renderContract(contract availabilityContract) []byte {
	data, err := json.Marshal(contract)
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func renderGo(contract availabilityContract) []byte {
	var source bytes.Buffer
	source.WriteString("// Code generated by misc/tests/contracts/generate; DO NOT EDIT.\n\npackage main\n\n")
	source.WriteString("var conditionMethodsByGOOS = map[string]map[string]struct{}{\n")
	writeMethodSet(&source, "freebsd", freeBSDConditionMethods)
	writeMethodSet(&source, "linux", contract.Linux)
	writeMethodSet(&source, "windows", contract.Windows)
	source.WriteString("}\n")
	source.WriteString("\nvar conditionRegexMethodsByGOOS = map[string]map[string]struct{}{\n")
	writeMethodSet(&source, "freebsd", freeBSDRegexConditionMethods)
	writeMethodSet(&source, "linux", legacyRegexConditionMethods)
	writeMethodSet(&source, "windows", legacyRegexConditionMethods)
	source.WriteString("}\n")
	writeConditionFieldSpecs(&source, contract)
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		panic(err)
	}
	return formatted
}

func writeMethodSet(buf *bytes.Buffer, goos string, methods []string) {
	fmt.Fprintf(buf, "\t%q: {\n", goos)
	for _, method := range methods {
		fmt.Fprintf(buf, "\t\t%q: {},\n", method)
	}
	buf.WriteString("\t},\n")
}
