package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"path/filepath"
	"sort"
)

const contractSchema = "condition-availability-v1"

var freeBSDConditionMethods = []string{
	"AccountLocked",
	"BasePackageInstalled",
	"BaseUpdateChecksEnabled",
	"Command",
	"CommandContains",
	"CommandOutput",
	"DirContains",
	"FileACL",
	"FileContains",
	"FileEquals",
	"FileFlagSet",
	"FileOwner",
	"FirewallAvailable",
	"FirewallEnabled",
	"FirewallRulesLoaded",
	"FirewallUp",
	"JailRunning",
	"KernelVersion",
	"PackageUpdateChecksEnabled",
	"PasswordAuthenticationDisabled",
	"PasswordChanged",
	"PathExists",
	"PermissionIs",
	"PkgAuditClean",
	"ProgramInstalled",
	"ProgramVersion",
	"RunningInJail",
	"ServiceEnabled",
	"ServiceUp",
	"SysctlValue",
	"UserExists",
	"UserInGroup",
}

var legacyRegexConditionMethods = []string{
	"CommandContains",
	"DirContains",
	"FileContains",
}

var freeBSDRegexConditionMethods = []string{
	"CommandContains",
	"DirContains",
	"FileContains",
	"ProgramVersion",
	"SysctlValue",
}

type availabilityContract struct {
	Schema  string   `json:"schema"`
	Linux   []string `json:"linux"`
	Windows []string `json:"windows"`
}

func discoverAvailability(root string) (availabilityContract, error) {
	linux, err := discoverMethods(root, "linux")
	if err != nil {
		return availabilityContract{}, err
	}
	windows, err := discoverMethods(root, "windows")
	if err != nil {
		return availabilityContract{}, err
	}
	return availabilityContract{Schema: contractSchema, Linux: linux, Windows: windows}, nil
}

func discoverMethods(root, goos string) ([]string, error) {
	ctx := build.Default
	ctx.GOOS = goos
	ctx.GOARCH = "amd64"
	ctx.CgoEnabled = false
	pkg, err := ctx.ImportDir(root, build.IgnoreVendor)
	if err != nil {
		return nil, fmt.Errorf("select %s files: %w", goos, err)
	}

	methods := make(map[string]struct{})
	fset := token.NewFileSet()
	for _, name := range append(pkg.GoFiles, pkg.CgoFiles...) {
		path := filepath.Join(root, name)
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if ok && isConditionMethod(fn) {
				methods[fn.Name.Name] = struct{}{}
			}
		}
	}

	names := make([]string, 0, len(methods))
	for name := range methods {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

func isConditionMethod(fn *ast.FuncDecl) bool {
	if fn.Recv == nil || len(fn.Recv.List) != 1 || fn.Type.Params.NumFields() != 0 || fn.Type.Results == nil || len(fn.Type.Results.List) != 2 {
		return false
	}
	receiver, ok := fn.Recv.List[0].Type.(*ast.Ident)
	if !ok || receiver.Name != "cond" {
		return false
	}
	first, firstOK := fn.Type.Results.List[0].Type.(*ast.Ident)
	second, secondOK := fn.Type.Results.List[1].Type.(*ast.Ident)
	return firstOK && secondOK && first.Name == "bool" && second.Name == "error"
}

func renderContract(contract availabilityContract) []byte {
	data, err := json.Marshal(contract)
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func renderGo(contract availabilityContract) []byte {
	var source bytes.Buffer
	source.WriteString("// Code generated by misc/tests/contracts/generate; DO NOT EDIT.\n\npackage main\n\n")
	source.WriteString("var conditionMethodsByGOOS = map[string]map[string]struct{}{\n")
	writeMethodSet(&source, "freebsd", freeBSDConditionMethods)
	writeMethodSet(&source, "linux", contract.Linux)
	writeMethodSet(&source, "windows", contract.Windows)
	source.WriteString("}\n")
	source.WriteString("\nvar conditionRegexMethodsByGOOS = map[string]map[string]struct{}{\n")
	writeMethodSet(&source, "freebsd", freeBSDRegexConditionMethods)
	writeMethodSet(&source, "linux", legacyRegexConditionMethods)
	writeMethodSet(&source, "windows", legacyRegexConditionMethods)
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		panic(err)
	}
	return formatted
}

func writeMethodSet(buf *bytes.Buffer, goos string, methods []string) {
	fmt.Fprintf(buf, "\t%q: {\n", goos)
	for _, method := range methods {
		fmt.Fprintf(buf, "\t\t%q: {},\n", method)
	}
	buf.WriteString("\t},\n")
}
